[package]
name = "usando-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
creando-macros = {path="../creando-macros"}
crear-proc-macro = {path="../crear-proc-macro"}