#+TITLE: Databases con SQLx y Postgres II


En la sesión anterior se realiza una conexión mediante un pool a
postgres, del cual se consultan la lista de ciudades y lista de
temperaturas.

El temario de esta sesión consiste en realizar los ejercicios
propuestos:

Propuestas de ejercicios (Tarea)

- crear comando para tener temperaturas
- que tenga un filtro por ciudad
- que tenga un filtro por fecha 'desde'

- comando para cargar datos a db, teniendo la ruta a csv.
- leer csv, cargar los datos a db creando los sql y ejecutando con
  sqlx.

Y crear *test* para las funciones que se realicen.

** Hacer migrations:

Primero se instala una herramienta de ayuda, que provee algunos
comandos de utilidad.

#+begin_src bash
cargo install sqlx-cli --no-default-features --features rustls,postgres
#+end_src

Migration  es la acción de crear toda la estructura de la database,
creando un registro de cambios que se va cargando consecutivamente.

Para iniciar se debe ejecutar:

#+begin_src bash
sqlx migrate add initial-tables
#+end_src

Y luego cargar el código *sql* en el archivo inicial, que sería:

#+begin_src sql
create table ciudad (
	   id serial primary key,
	   pais varchar(50) not null,
	   nombre varchar(50) not null
);
alter table ciudad  add unique (pais, nombre);

create table temperatura (
	   id serial primary key,
	   ciudad_id serial not null,
	   fecha date not null,
	   temperatura double precision not null,
	   constraint fk_ciudad foreign key (ciudad_id) references ciudad (id)
);
alter table temperatura add unique (ciudad_id, fecha);
#+end_src

Luego, se aplica la migración con:

#+begin_src bash
sqlx migrate run
#+end_src

Si se desean cambios en las tablas, agregar nueva etapa de
migraciones:

#+begin_src basj
sqlx migrate add -r <name>
#+end_src

Este comando requiere que esté definida la variable *DATABASE_URL* en
el archivo *.env*.
