[package]
name = "search_numeros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = { version = "2.2.0", features = ["use_core"] }
regex = "1.7.1"
