[package]
name = "crear-proc-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.27"
syn = { version = "2.0.16", features = ["full", "extra-traits"] }
creando-macros = {path="../creando-macros"}