[package]
name = "data_struct"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
packed_struct = { version = "0.10.1", features = ["serde", "serde_derive", "use_serde"] }
serde = { version = "1.0.163", features = ["derive", "serde_derive"] }
