#+TITLE: Ejercicios de C
#+STARTUP: latexpreview
#+OPTIONS: tex:t

* Básico

#+name: ejemplo1
#+begin_src C includes <stdio.h>
printf("mi primer programa en C");
#+end_src

#+RESULTS: ejemplo1
: mi primer programa en C


Ejemplo con números y formatos

#+name: ejemplo2
#+begin_src C :results scalar includes <stdio.h>
float x = 6.2555, z = 7.2576;
int y = 4, t = -5;
printf("Valores x:%4.2f \n z: %5.2e \n y:%5d \n t:%d", x, z, y, t);
#+end_src

#+RESULTS: ejemplo2
: Valores x:6.26 
:  z: 7.26e+00 
:  y:    4 
:  t:-5

#+RESULTS:


Ingresar 4 valores y mostrarlas invertidas

#+begin_src C :results scalar :includes <stdio.h> :tangle ingresa_invertir.c
void main(void){
 int A,B,C,D;
 printf("Ingrese cuatro datos de tipo entero\n");
 scanf("%d %d %d %d\n", &A, &B, &C, &D);
 printf("%d %d %d %d\n", D, C, B, A);
}
#+end_src

#+RESULTS:
: Ingrese cuatro datos de tipo entero
: 32765 -1375464080 21906 575357120

Ingresar los sueldos de 6 meses de usuario, caucluar valor promedio.

#+begin_src C :results scalar :includes <stdio.h> :tangle sueldo_semestral.c
void main(void){
  int CLA;
  float SU1, SU2, SU3, SU4, SU5, SU6, ING, PRO;
  printf("Ingrese la clave del empleado y los 30 sueldos: \n");
  scanf("%d %f %f %f %f %f %f", &CLA, &SU1, &SU2, &SU3, &SU4, &SU5, &SU6);
  ING = (SU1 + SU2 + SU3 + SU4 +SU5 + SU6);
  PRO= ING/6;
  printf("ID: %d Ingreso Total:  %5.2f Promedio: %5.2f \n", CLA, ING, PRO);
  }
#+end_src


Superficie de un triángulo

#+name: suptr
#+begin_src C :results scalar :includes <stdio.h> :tangle sup_triangulo.c
void main(void){
  float BAS, ALT, SUP;
  printf("Ingrese la base y altura de tríangulo: \n");
  scanf("%f %f", &BAS, &ALT);
  SUP = BAS * ALT / 2;
  printf("La superficie del triángulo es: %5.2f \n", SUP);
}
#+end_src

#+RESULTS: suptr
: Ingrese la base y altura de tríangulo: 
: La superficie del triángulo es:  0.00 


** Problema PR1

#+name: pr1
#+begin_src C :results scalar :includes <stdio.h> :tangle pr1.c
  printf("pr1\n");
  int i=5, j=7, k=3;
  int m1;
  float x=2.5, z=1.8;
  float t;
  m1=((j % k)/2)+1;
  m1 += i;
  m1 %= --i;
  printf("El valor de m1 es: %d\n", m1);
  t = ((float) (j % k) / 2);
  t++;
  x *= ++z;
  t -= (x += ++i);
  printf("El valor de t es: %.2f\n",t);
#+end_src

#+RESULTS: pr1
: pr1
: El valor de m1 es: 2
: El valor de t es: -10.50

** Problema PR2

#+name: pr2
#+begin_src C :results scalar :includes <stdio.h> :tangle pr2.c
  int i= 15, j, k, l;
  
  j = (15 > i--) > (14 < ++i);
  printf("Valor de j es: %d\n", j);

  k = ! ('b' != 'd') > ( !i - 1);
  printf("El valor de k es: %d\n", k);

  l = (!(34 > (70%2)) || 0);
  printf("El valor de l es: %d\n",l);
#+end_src

#+RESULTS: pr2
: Valor de j es: 0
: El valor de k es: 1
: El valor de l es: 0

Problema PR3

** Datos en pies y libras, convertir a metros y kilos

#+begin_src C :results scalar :includes <stdio.h> :tangle pr3.c
void main(void){
float PIE, LIB, MET, KIL;
printf("Ingrese los datos del objeto: \n");
 scanf("%f %f", &PIE, &LIB);
 MET = PIE * 0.09290;
 KIL = LIB * 0.45359;
 printf("Datos de objeto \nLongitud: %5.2f \t Peso: %5.2f\n", MET, KIL);
 }
#+end_src

** Superficie y volumen de cilindro.

#+begin_src C :results scalar :includes <stdio.h> <math.h> :tangle cilindro.c
void main(void){
float RAD,ALT,VOL,ARE;
 printf("Ingrese el radio y la altura del cilindro:\n");
 scanf("%f %f", &RAD, &ALT);
 VOL = M_PI * pow(RAD,2) * ALT;
 ARE = 2 * M_PI * RAD * ALT;
 printf("El volumen es %6.2f \t El área es: %6.2f \n", VOL, ARE);
}
#+end_src


** Acres a hectareas

#+begin_src C :results scalar :includes <stdio.h> :tangle terreno.c
void main(void){
float ECA;
 printf("Ingrese la extension de la estancia: \n");
 scanf("%f", &ECA);
 ECA = ECA * 4047/10000;
 printf("La extension en hetareas es: %5.2f", ECA);
}
#+end_src


** Area de triangulo en base a sus lados.

#+begin_src C :results scalar :includes <stdio.h> <math.h> :tangle triangulo.c
void main(void){
  float LA1, LA2, LA3, AUX, ARE;
  printf("Ingresa los lados del triángulo: \n");
  scanf("%f %f %f", &LA1, &LA2, &LA3);
  AUX=(LA1 + LA2 + LA3)/2;
  ARE = sqrt (AUX * (AUX-LA1) * (AUX-LA2) * (AUX-LA3));
  printf("El área del triángulo es: %6.2f \n", ARE);
  }
#+end_src




** Perímetro dados dos puntos


Construye un diagrama de flujo que, al recibir como datos las coordenadas de los
puntos P1, P2 y P3 que corresponden a los vértices de un triángulo, calcule su
perímetro.

Datos: X1, Y1, X2, Y2, X3, Y3 (variables de tipo real que representan las
coordenadas de los puntos P1, P2 y P3 ).

Consideraciones:
• Para calcular la distancia DIS entre dos puntos dados P1 y P2 aplicamos la siguiente
fórmula:

Distancia entre dos puntos.

\begin{equation}                        % arbitrary environments,
DIS = \sqrt { (X1 - X2) ^ 2 + (Y1 - Y2) ^ 2}
\end{equation}                          % etc

#+begin_src C :results scalar :includes <stdio.h> <math.h> :tangle perimetro_triangulo.c
void main(void){
float X1, Y1, X2, Y2, X3, Y3, LA1, LA2, LA3, PER;
 printf("Ingresa la coordenada para punto P1:\n");
 scanf("%f %f", &X1, &Y1);
 printf("Ingresa la coordenada para punto P2:\n");
 scanf("%f %f", &X2, &Y2);
 printf("Ingresa la coordenada para punto P3:\n");
 scanf("%f %f", &X3, &Y3);
LA1 = sqrt (pow (X1-X2,2) + pow (Y1-Y2,2) );
LA2 = sqrt (pow (X2-X3,2) + pow (Y2-Y3,2) );
LA3 = sqrt (pow (X1-X3,2) + pow (Y1-Y3,2) );
PER =  LA1 + LA2 + LA3;
 printf("El perímetro del tríangulo es: %6.3f\n", PER); 
}
#+end_src



* Ejercicios

** rev1

#+begin_src C :results scalar :includes <stdio.h> :tangle rev1.c
int i,j,k=2, l=7;

 i = 9 + 3*2;
 j = 8%6 + 4*2;
 i %= j;
 printf("El valor de i es: %d\n", i);

 ++l;
 --k;
 k -= l++ * 2;
 printf("El valor de k es: %d\n", k);

 i = 5.5 - 3*2 % 4;
 j = (i*2-(k=3, --k));
 printf("El valor de j es: %d\n", j);
#+end_src

#+RESULTS:
: El valor de i es: 5
: El valor de k es: -15
: El valor de j es: 4

** rev2

#+begin_src C :results scalar :includes <stdio.h> :tangle rev2.c
int i=5, j=4, k, l, m;
k = !i*2 + --j *2 -3;
printf("El valor de k es: %d \n", k);

l = ! (!i ||  1 && 0) && 1;
printf("El valor de l es: %d \n", l);

m = (k=(!(12>10)), j=(10||0) && k, (! (k || j)));
printf("El valor de m es : %d \n", m);
#+end_src

#+RESULTS:
: El valor de k es: 3 
: El valor de l es: 1 
: El valor de m es : 1 


** rev3

Operar dos valores con suma, resta, multiplicaición.


#+begin_src C :results scalar :includes <stdio.h> :tangle rev3.c
void main(void){
  float a, b;
  printf("Ingresa dos valores a operar:\n");
  scanf("%f %f", &a, &b);
  printf("La suma es: %6.3f \n", b+a);
  printf("La resta es: %6.3f \n", b-a);
  printf("La diferencia es: %6.3f \n", b*a);
}
#+end_src


** rev4

Calcular el cambio de un producto dado lo que se entrega.

#+begin_src C :results scalar :includes <stdio.h> :tangle rev4.c
const float COSTO = 140;

void main(void){
 float PAGAR, VUELTO;
 printf("El valor es %6.2f", COSTO);
 printf("Cuánto vas a pagar?\n");
 scanf("%f", &PAGAR);
 VUELTO = PAGAR-COSTO;
 printf("El vuelto será: %f\n", VUELTO);
}
#+end_src


** rev5: circulo

Area y perímetro de círculo

#+begin_src C :includes <stdio.h> <math.h> :tangle rev5.c
void main(void){
  float RADIO, AREA, PERIMETRO;
  printf("Ingresa radio del círculo:\n");
  scanf("%f", &RADIO);
  AREA = M_PI * pow (RADIO, 2);
  PERIMETRO = 2 * M_PI * RADIO;
  printf("Area %6.3f\n", AREA);
  printf("Perímetro %6.3f\n", PERIMETRO);  
}
#+end_src


** reve6: cambio dolar

#+begin_src C :includes <stdio.h> :tangle rev6.c
void main(void){
 const float valor=12.48;
 float cantidad, total;
 printf("Ingresa cantidad de dolares a cambiar:\n");
 scanf("%f", cantidad);
 total =  cantidad * valor;
 printf("El cambio será de $ %6.3f", total);
}
#+end_src

** rev8: velocidad km/hr

#+begin_src C :includes <stdio.h> :tangle rev8.c
void main(void){
  float DIS,MIN,SEG,CEN,TSE,VMS,VKH;
  printf("Ingresa los valores de distancia, min, seg, cen");
  scanf("%f %f %f %f", &DIS, &MIN, &SEG, &CEN);
  TSE=MIN*60+SEG+CEN/100;
  VMS=DIS/TSE;
  VKH=VMS*3600/1000;
  printf("La velocidad final será %6.2f", VKH);
}
#+end_src


** rev8: segundos en dias


#+begin_src C :includes <stdio.h> :tangle rev9.c
void main(void){
const int SEGDIA=24*60*60;
 int SEGUNDOS, DIAS;
 printf("Cantidad de dias:\n");
 scanf("%d", &DIAS);
 SEGUNDOS=SEGDIA*DIAS;
 printf("Total segundos %d\n", SEGUNDOS);
}
#+end_src

** rev10: numero a digitos

#+begin_src C :includes <stdio.h> :tangle rev10.c
void main(void){
int i=0;
int NUM, DIG;
printf("Escribe un número de 4 dígitos\n");
scanf("%d",&NUM);
DIG=(NUM - NUM%1000)/1000;
NUM=NUM%1000;
printf("%d\n",DIG);
DIG=(NUM-NUM%100)/100;
NUM=NUM%100;
printf("%d\n",DIG);
DIG=(NUM-NUM%10)/10;
NUM=NUM%10;
printf("%d\n",DIG);
DIG=NUM;
printf("%d\n",DIG);
}
#+end_src


** rev11: cono, areas y volumen

#+begin_src C :includes <stdio.h> <math.h> :tangle rev11.c
void main(void){
  float RADIO, ALTURA, BASE, GENE, LATERAL, SUP_CONO, VOL_CONO;
  printf("Ingresa radio y altura\n");
  scanf("%f %f", &RADIO, &ALTURA);
  BASE = M_PI * pow (RADIO, 2);
  GENE = sqrt( pow (RADIO,2) + pow (ALTURA,2)); 
  LATERAL = M_PI * RADIO * GENE;
  SUP_CONO = BASE + LATERAL;
  VOL_CONO = (1/3)*BASE*ALTURA;
  printf("Superficie cono: %f, Volumen cono: %f", SUP_CONO, VOL_CONO);
}
#+end_src


* Estructuras algoritmicas (Cap2)


** Uso de if

#+name: promedio
#+begin_src C :includes <stdio.h> <math.h>
float promedio;
promedio = 8;
if (promedio>=6){
  printf("Aprobado!");
 }
#+end_src

#+RESULTS: promedio
: Reprobado!


*** Precio de un producto

Si el valor es inferior a 1500, incrementar 11%, mostrar precio final

#+begin_src C
float valor, valor_final;
valor = 1200;
valor_final = valor;
if (valor<=1500){
  valor_final = valor*1.1;
 }
printf("Valor fianl es %f", valor_final);
#+end_src

#+RESULTS:
: Valor fianl es 1320.000000

** Uso de else

#+name: promedio2
#+begin_src C :includes <stdio.h> <math.h>
float promedio;
promedio = 4;
if (promedio>=6){
  printf("Aprobado!");
 } else {
  printf("Reprobado!");
 }
#+end_src

#+RESULTS: promedio2
: Reprobado!


*** Precio de un producto

Si el valor es inferior a 1500, incrementar 11%, mostrar precio final, un 8% si es mayor.

#+name: valorfinal2
#+begin_src C
float valor, valor_final;
valor = 1600;
if (valor<=1500){
  valor_final = valor * 1.11;
 }
else{
  valor_final = valor * 1.08;
 }
printf("Valor final es %f", valor_final);
#+end_src

#+RESULTS: valorfinal2
: Valor fianl es 1728.000000


** Uso de switch

Construir un diagrama de flujo y el correspondiente programa en C.


#+begin_src C :results output :includes <stdio.h> <math.h> :libs -lm  :tangle usoswitch.c 
float T;
int OP;
float RES;
printf("Ingresa la opción de calculo y el valor entero: ");
T=13;
OP=1;
switch(OP){
  case 1:
    RES=T/5;
    break;
  case 2:
    RES= pow(T,T);
    break;
  case 3:
  case 4:
    RES = 6 * T / 2;
    break;;
  default:
    RES = 1;
    break;
 }
printf("Resultado : %7.2f\n", RES);
#+end_src

#+RESULTS:
: Ingresa la opción de calculo y el valor entero: Resultado :    2.60


** Uso switch en base a casos de una tabla

| Nivel | Incremento[%] |
|-------+---------------|
|     1 |           3.5 |
|     2 |           4.1 |
|     3 |           4.8 |
|     4 |           5.3 |
|-------+---------------|



#+begin_src C :results output :includes <stdio.h> <math.h> :libs -lm  :tangle usoswitch.c 
void main(void){
float SAL;
int NIV;
printf("Ingrese nivel académico del profesor: \n");
scanf("%d", &NIV);
printf("Ingrese el salario: \n");
scanf("%f", &SAL)
switch(NIV){
case 1: SAL = SAL * 1.035; break;
case 2: SAL = SAL * 1.041; break;
case 3: SAL = SAL * 1.048; break;
case 4: SAL = SAL * 1.053; break;    
 }
printf("Nivel :%d, salario: %8.2f\n", NIV,SAL);
 }
#+end_src



** Fibonacci


$$
a_{n+1} =  a_{n} + a_{n-1}
$$
